[[Btop]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f03d2933c4a6485cb3b7fedd677c0e46e2ff1e76"
os = "macos"

    [[Btop.download]]
    sha256 = "5ea6dc71283ad67c1cdba44e07288d5f50433f99b7c10219d9d572c89d980afc"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.aarch64-apple-darwin-cxx03.tar.gz"
[[Btop]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "baab7e4862b673e8659b8941c6e31c47b26f9270"
os = "macos"

    [[Btop.download]]
    sha256 = "74bdd8292ebc462d89b82abcc0a65cede92e44ee819812995e15ff243c150c6a"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.aarch64-apple-darwin-cxx11.tar.gz"
[[Btop]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5132bd3f03321f81234699c74c614dc3459651e0"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "f978233ae1765fda87e6e16159202fd01214a0f17c25d75f5d39e834c7071b44"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.aarch64-linux-gnu-cxx03.tar.gz"
[[Btop]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd5256041209d8a2e65c0fb2b09a765eb84ffb5d"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "57d62ab79cb0e8ea3d6bebd81d7674dbed5f34587c39b7e47cfd0f8bc56453d3"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.aarch64-linux-gnu-cxx11.tar.gz"
[[Btop]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87cf56cf624e10cf49ac66a9c7bb2bc7c3627c55"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "d2a8d9b18586ed5dfbad3be104c69d352747b5beb3739ac49e57e85a82d84c59"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.aarch64-linux-musl-cxx03.tar.gz"
[[Btop]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50dd4f6b5dd210073ad450b785395119b1387c81"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "bd02b0847a9064d5935cfe73c70ec8eecf4811eccbed3551c1b263c05ec3a78d"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.aarch64-linux-musl-cxx11.tar.gz"
[[Btop]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2fc58f5cae849b79697e1a1d8e8816f15547662"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "6fbc04752c174fd81ee2c2ce868bbbc95169599b95445756c2dc37140950f84e"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Btop]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b93b53e65caad5825b8e2f431505385fe094d4b"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "8a5c84c62d5dae7b27a1d51ff46e99a9802316de341fe5e9e42fd2aeb4f0e3be"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Btop]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "828f0cc8ef1f77c3a1c97320dcc8f9b7382f460b"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "9879b456678854c7d0b82ae7c6c3b13d05626e69c9581f91bda308d3828e3155"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Btop]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22a69dcce83eb9479b8948de3478efabf4bb9999"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "f65c70c0da40ad3b357f80fc87b556b884c8323f1fdfc873bfcba433df2b36e6"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Btop]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f74d6995d6ce4068376c2f20f331cba0cad98e93"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "75bd3fcb0d38677c566c3c1be9402e97b44d0e4841e0e5d580e6fc1a787d95a4"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Btop]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46c53783dddb740ed0138cb32ef120f69fcd0671"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "d8da9f46d1d1c3cfa9fda4ad60da5fe6c02d577ff3f81d791232b9e6025e9b98"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Btop]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c645876f6bfc859eb92299ee60cd6466e23887a"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "8bf1fec8285906d5761b29045f8bc00953dc260f595bc8d13c0ab7b29bc95ea6"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Btop]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "695d5a7c96e438df13b332625f796e74b45f5f5b"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "24223d0458b6ae91f3da03bf5cc16bed6c9fd92503dd613581dcf872da6f376d"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Btop]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d22c4ae9f8a20ee73d3a4c12ee147fae04231c9c"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "1d63c4b12d35a54faca847c30a05b02f3e8a961425ca2f36c37b07c8c07f7f69"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.i686-linux-gnu-cxx03.tar.gz"
[[Btop]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce461533e344e5ba90595b1fd0f3bb090c65ccdf"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "fd255b45d355934d80fd4974b589e6601a93967c3f2f8cf7d5a6e58c2bb564a4"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.i686-linux-gnu-cxx11.tar.gz"
[[Btop]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6384a95592e13578cafda12038c921cf91ad629"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "bcbd8624058edef54707f732391b392b0d6c4b1fd929553388e877ef2cfbcffc"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.i686-linux-musl-cxx03.tar.gz"
[[Btop]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81ccd166a5d434e108e3939b7913fb98f4e28aad"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "42f2cf0fb1bcd707922aadd6c6ef4096920527a039e32b671fd44d05a6367081"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.i686-linux-musl-cxx11.tar.gz"
[[Btop]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "399fec147b7527ca685c8eacd55ef1b48a21016f"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "3959ec1a9e2a611ef0479f193c6ac57ddaaeca4c16062e6bc668bbbc301195f0"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Btop]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c14e152ebdbacb74d55fdfc5d8b217b3b9d00f3e"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "4ca72d46e03d4e6526b5490b94be138dd27566bc56dc363282f259fbae809a57"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4aff5ca75cd50636745c8bf7ccf67c14bc6af351"
os = "macos"

    [[Btop.download]]
    sha256 = "9cce6dfedbfb5ac27728507ced4f0a5dee2ba676c6d4172aad132f0e35307c11"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.x86_64-apple-darwin-cxx03.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b081a8f8c965a669abb5e44ac5604c5218a4e3d8"
os = "macos"

    [[Btop.download]]
    sha256 = "6ca699b8f196a6222217ee4dd5c5d21ebd9103e7c53ac92194b3063fab5f470e"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.x86_64-apple-darwin-cxx11.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d6097b00df99dbdac88d6c14a6f0aa501ed44a3"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "9f6e204fb6b15032d15fe5ebc194d5ddfae931c0cb44aff4171217fb107264d4"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.x86_64-linux-gnu-cxx03.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "719d68e3d2c8493bdbfa0da669418094cb2ac043"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "67f5162ecc6822c9b15904682aaca5bc4e89634ad63163e1b089de7387f25041"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.x86_64-linux-gnu-cxx11.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c71cc9d55ab5bb0375efc23e530daae3b6618f0"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "a7e1177130f4e5c803fd88f8340679af5ce10fe2a32cdf002adf11ebd2ad55af"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.x86_64-linux-musl-cxx03.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "515fb10d5e7123edc71204fe6553cf308301a19f"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "7902dbc36ffdd5272ceb0c12205b71227adbeb3b940196050676f95cbc43452b"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.x86_64-linux-musl-cxx11.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac4558feb32b59db0c0bd67c64de1490d4aa8ae7"
os = "freebsd"

    [[Btop.download]]
    sha256 = "a5573c4b1fb7a819fc9a8ff1aa6951654155778ffef899b9f4eaa038677b7d16"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.x86_64-unknown-freebsd-cxx03.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e1fb1d5ade9fb290f8a4bfcdb9e38651f925d9c"
os = "freebsd"

    [[Btop.download]]
    sha256 = "ffd69cb32fbbaf75a0cf4b7842be4a639b1460147fd38b5f13e08a3f84f3f851"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.2.8+0/Btop.v1.2.8.x86_64-unknown-freebsd-cxx11.tar.gz"
