[[Btop]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "446e7d5deb3f4bfdadf6e986675caff983019c1e"
os = "macos"

    [[Btop.download]]
    sha256 = "d68f62cda1a4fcaa83e87919ed514d02420efc1c7b3fae2d86192f815a5856fa"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.aarch64-apple-darwin-cxx11.tar.gz"
[[Btop]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c371435735e68f169f6730d5d6a289e45b7540a"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "7d728edfeda42a084dd09cf195d328c0ccfdcd6baee542ad8621c36143cd5d21"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Btop]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d4beec92e8e2e62e9d7f71f41ea1620fd849680"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "63686229f50362aee4c2e7a0cb0b4e366c734e153787bc5681343ba6fc34d1e4"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Btop]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f35f0c97584816d9edb300c89b9d9b1c49373cd"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "8dd8b087f4ac182dd4c52686b817fdb0c5cc7f5ee15232822ea6c44dabc72a37"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.aarch64-linux-musl-cxx03.tar.gz"
[[Btop]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d432c693168d8425ed65b952e301aa3f8b4fdd87"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "a6d039f947b6323b04c7500c65ca526c5e6537030d9f37320f0db7018d252ad6"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.aarch64-linux-musl-cxx11.tar.gz"
[[Btop]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3edaed2ea27d5b7a107f2c3f01cc13b607344455"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "31e44c3e2022811e618431e7c0807d41739d1aecb0ffc27e89a24a810a2498c3"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Btop]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0785bf58f132c91bc0632544aee8dbe0c5fc10cc"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "42937e4b974a60240351baf2b251bf3ce81fa7d34af291115d6d70521e43a293"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Btop]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "006c1531e3b1aad5664b80fef0c0f8508cd35889"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "ea539ae97790e182935e313f9bd63bc6007a14ace093b0c87d23085a89cb6074"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Btop]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ce5e0e865ab72fa4201b457700059d194aaf81f"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "232dd17b43e8dffce6977cc9bd9d807647e5e339e604a181f08e24cee7a825e2"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Btop]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a91b8a3e64ddd0024c1e91133a07928c41533f2"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "fe2cbb7a1c6aad1e8f13f40da815774ca0edfdf05e45607c7fdb897db8b828c8"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Btop]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "028d4cb7c8f198a0088977407343f5f9a5769c7e"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "012fddb6c12900fa444bd11ea86bd88c87f6d7dae85f28651161bd80aea2be12"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Btop]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48bd12223d3730fc0d6e00a9912b161633f59526"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "2a10761bc139148f21fea0bb0e33ec7acea75e0f3b5579efa2a19fd402b5bbfd"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Btop]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9abdbb3257dc06a3cc81eefb2464ed1a67c1c124"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "5ad6443562aeed6434f39f2495ef908cd84d4a39cd53911e25a006f1f126e871"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Btop]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "026e828967be0b7923bfccb6e52eaac620dd71e0"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "b19985385a424ff3aeac86722dbaa868007138706abb95466fcab70df975d871"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.i686-linux-gnu-cxx03.tar.gz"
[[Btop]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20940f52472d6d17432d28d83a5c49fd3a17f860"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "6f860fcd7524673bf747223aa0c326bda14710603870cccca97c07c6b69d5bf1"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.i686-linux-gnu-cxx11.tar.gz"
[[Btop]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0cc8fca0d75947bb0c1f8c0872d7b2cabdcdb924"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "f41a9f4ae5a2e4e10295b39bd50bc5428d679186e5a4934eba866676a0cd5bcb"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.i686-linux-musl-cxx03.tar.gz"
[[Btop]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86f2ae46c844b10d916292296953cfd4352c8b78"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "9e28be1a81f687cde0ac3e92ed2360ce2243302e79296cc79292fcc8377e4d82"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.i686-linux-musl-cxx11.tar.gz"
[[Btop]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9ba17cb7dace2c1f4a9c3d29129c44e64f4c777"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "a30c66588bfad024339495a7236780908e752b4d94dcd704bcad524ef84ee7b5"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Btop]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98f89362f4e5081777b33843c3a3402bfe51b6d2"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "51b72b8ab0851d1cfda40d482a749df9ed127b87d702472e0a0efb6ab1b3a868"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea7444c5473ed330b9953f06bfb14396da901b36"
os = "macos"

    [[Btop.download]]
    sha256 = "76d2ec15aa4e7c4f22cb9fcfca755fe4e8b8acf504117219ec1012cd4e59b6ce"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.x86_64-apple-darwin-cxx03.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2fda1901e8a9494cee05b06ee59f4ef334f7722"
os = "macos"

    [[Btop.download]]
    sha256 = "f52e5c52602f061f06048ac317e1b45ddc89f4111e0be383a1b18bcced83386e"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.x86_64-apple-darwin-cxx11.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbb0636519b0e064621ed1bedab388380fb337b1"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "9d49f1c23557c7620b7d0b2495690b22fd811baa52aea2ca55df7c8d03222baf"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ecef643d0f9ad32efec250cdfa4ce8a3bb7a96e4"
libc = "glibc"
os = "linux"

    [[Btop.download]]
    sha256 = "06d31a1ae7fed75e0d5fc850c0035576aa5fa408f228fff66c6e501c6629d0a5"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d9450add1130c112801155903369cfee38d2845"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "dbbe1faba28648a43f66d4902fd715780e63b597ec730c7f9ca89f3fddd1c4c4"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.x86_64-linux-musl-cxx03.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8680b553c2302096f69a70609f27f9a24a27ef1"
libc = "musl"
os = "linux"

    [[Btop.download]]
    sha256 = "76dc3b3e69a2b0f67911204d21c0146a12e4e9c5c1831d27909f69a3eda0db2b"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.x86_64-linux-musl-cxx11.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e4f118b520500f2d8b71a73fd8ec1c634a3ef73"
os = "freebsd"

    [[Btop.download]]
    sha256 = "03bb0db9187103ec05643dbe95c54d1186d62505b596027908a281a4101b5c9d"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.x86_64-unknown-freebsd-cxx03.tar.gz"
[[Btop]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "398ea911574b7aa7885e6f10761e88d58a1a7646"
os = "freebsd"

    [[Btop.download]]
    sha256 = "c7e3a812435ef95ed48de897dabcafba63f45444b4ce380715a5b2c8da955bce"
    url = "https://github.com/JuliaBinaryWrappers/Btop_jll.jl/releases/download/Btop-v1.3.2+0/Btop.v1.3.2.x86_64-unknown-freebsd-cxx11.tar.gz"
